version: '2.1'
volumes:
  grafana-pgdata:
services:
  # Grafana dedicated storage
  #
  grafana-storage:
    image: postgres:10-alpine
    volumes:
      - grafana-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=grafana
    healthcheck:
        test: ["CMD", "pg_isready"]
        interval: 30s
        timeout: 1s
        retries: 5

  # Grafana Server
  #
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=grafana-storage
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=admin
      - GF_DATABASE_PASSWORD=password