version: '2'
# Configure a dedicated volume for storing Portainer's configuration
#
volumes:
  portainer_data:
services:
  # Configure Portainer service
  #
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - local    
  # Configure NGinx proxy service
  #
  nginx:
    build: docker/
    ports:
      - "80:80"
    depends_on:
      - portainer    
    restart: always
    networks:
      - local
# Link network to the docker bridge driver
#
networks:
  local:
    driver: bridge