version: '3'
volumes:
  mysql-data:
services:
  mysql:
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=tutorial
      - MYSQL_RANDOM_ROOT_PASSWORD=true
  php:
    build: ../
    depends_on:
      - mysql
    volumes:
      - ./src:/project
    user: "${UID:-1000}:${GID:-1000}"
    command: php -v && composer --version